#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Greeking
version:      0.11
version_from: lib/Text/Greeking.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
