--- #YAML:1.0
name:               Text-Greeking
version:            0.12
abstract:           a module for generating meaningless text
author:
    - Timothy Appnel <tima@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006
resources:
    bugtracker:  http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Greeking
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/tima/perl-text-greeking
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
